const { sequelize } = require("./config/database")
const AudioBots = require("./models/AudioBots")
const BotPackages = require("./models/BotPackages")
const CompanyList = require("./models/CompanyList")
const ManagerBotPanels = require("./models/ManagerBotPanels")
const MusicBotPanels = require("./models/MusicBotPanels")
const Permissions = require("./models/Permissions")
const Radios = require("./models/Radios")
const Ranksystems = require("./models/Ranksystems")
const ServerPackages = require("./models/ServerPackages")
const Servers = require("./models/Servers")
const TsManagerBots = require("./models/TsManagerBots")
const UsedPorts = require("./models/UsedPorts")
const Users = require("./models/Users")
const RefreshTokens = require("./models/RefreshTokens")
const Tokens = require("./models/Tokens")

sequelize.sync({ alter: true }).then(() => {
    console.log("Database synced!")
})
